env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-useless-escape: 'off'
  typescript-eslint/no-unused-vars: 'off'
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  "@typescript-eslint/no-this-alias":
    - error
    - allowedNames:
      - self
